Het programma bevat een parser voor command line argumenten, waarmee een inventarisbeheerprogramma kan worden uitgevoerd. Via main.py zijn de hoofdopties op te vragen. Met ”main.py -h” is een lijst met opties in het hoofdmenu op te vragen en met “main.py [gekozen optie] -h zijn de benodigde argumentenin het submenu op te vragen. 
Hieronder worden de beschikbare opties en argumenten beschreven:
•	inventory_list: Deze optie toont een lijst van de huidige inventaris. Met het optionele argument '--file_name' kan de lijst worden geëxporteerd naar een csv-bestand. Geef hiervoor de gewenste bestandsnaam op.
•	product_detail: Deze optie toont de details van een specifiek product. Geef hiervoor de naam van het product op met de optie '-product_name'.
•	expired_list: Deze optie toont een lijst van alle vervallen producten in de inventaris. Net als bij 'inventory_list' kan deze lijst worden geëxporteerd naar een csv-bestand met behulp van de optie '--file_name'.
•	date_range: Deze optie toont een lijst van gekochte of verkochte producten binnen een opgegeven datumreeks. Geef hiervoor de begin- en einddatum van de gewenste periode op met de opties '-start_date' en '-end_date'. Gebruik de optie '-bought_sold' om aan te geven of u de gekochte of verkochte producten wilt zien. Geef 's' op voor de verkochte producten en 'b' voor de gekochte producten. Net als bij de andere opties kan deze lijst worden geëxporteerd naar een csv-bestand met behulp van de optie '--file_name'.
•	profit: Met deze optie kunt u de winst berekenen over een opgegeven datumreeks. Geef hiervoor de begin- en einddatum van de gewenste periode op met de opties '-start_date' en '-end_date'.
•	inventory_count: Deze optie telt het aantal van elk product in de inventaris.
•	plot_sold_graph: Met deze optie kunt u een grafiek maken van het aantal verkochte producten per dag binnen een opgegeven datumreeks. Geef hiervoor de begin- en einddatum van de gewenste periode op met de opties '-start_date' en '-end_date'.
•	add_bought: Met deze optie kunt u een nieuw product toevoegen aan de gekochte productenlijst. Geef hiervoor de naam van het product, de aankoopprijs en de vervaldatum op met de opties '-name', '-buy_price' en '-expiration_date'. Elke product krijgt een eigen id.
•	add_sold: Met deze optie kunt u een product toevoegen aan de verkochte productenlijst. Geef hiervoor het ID van het gekochte product en de verkoopprijs op met de opties '-bought_id' en '-sell_price'. Elk verkocht product krijgt een eigen id.
